kind: pipeline
type: docker
name: terraform-infrastructure

environment:
  ### -----------------------
  ### Available in all steps, change app_name to your app_name
  TF_VAR_app_name: tfmonorepo
  ### -----------------------

steps:
  - name: prepare-files-folders
    when:
      branch:
        - development
        - staging
        - production
    image: ubuntu:18.04
    commands:
      - mkdir -p ${DRONE_BRANCH}/
      - cp live/*.${DRONE_BRANCH} ${DRONE_BRANCH}/
      - cp live/*.tf ${DRONE_BRANCH}/
      - cp live/*.tpl ${DRONE_BRANCH}/ 2>/dev/null || true
      - mv ${DRONE_BRANCH}/backend.tf.${DRONE_BRANCH} ${DRONE_BRANCH}/backend.tf

  - name: terraform-apply
    when:
      branch:
        - development
        - staging
        - production
    depends_on:
      - prepare-files-folders
    image: unfor19/drone-terraform:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id_${DRONE_BRANCH}
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key_${DRONE_BRANCH}
    settings:
      actions:
        - validate
        - plan
        # - apply
        - destroy
      root_dir: ${DRONE_BRANCH}/
      vars:
        environment: ${DRONE_BRANCH}
