version: 2.1
workflows:
  pipeline:
    when:
      condition:
        or:
          - equal: [circleci, << pipeline.git.branch >>]
          # - equal: [development, << pipeline.git.branch >>]
          # - equal: [staging, << pipeline.git.branch >>]
          # - equal: [production, << pipeline.git.branch >>]
    jobs:
      - terraform-apply

jobs:
  terraform-apply:
    machine: true
    steps:
      - checkout
      - run:
          name: terraform-apply
          command: |
            declare -n AWS_ACCESS_KEY_ID_SECRET_NAME=aws_access_key_id_${CIRCLE_BRANCH}
            declare -n AWS_SECRET_ACCESS_KEY_SECRET_NAME=aws_secret_access_key_${CIRCLE_BRANCH}
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_SECRET_NAME}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_SECRET_NAME}
            docker run --rm -w="/code" -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e CIRCLE_BRANCH -v "${HOME}"/project/:/code/ unfor19/terraform-alpine:0.12.28 /code/scripts/tf-apply-circleci.sh
